// Code generated by command: go run asm.go -out filter.s -stubs filter_stub.go. DO NOT EDIT.

#include "textflag.h"

// func NumFilled(entries []byte) uint
TEXT ·NumFilled(SB), NOSPLIT, $0-32
	MOVQ entries_base+0(FP), AX
	MOVQ entries_len+8(FP), CX
	XORQ DX, DX

loop:
	CMPQ CX, $0x00
	JE   done
	CMPQ (AX), $0x00
	JE   increment
	INCQ DX

increment:
	INCQ AX
	DECQ CX
	JMP  loop

done:
	// Store filled to return value.
	MOVQ DX, ret+24(FP)
	RET
