// Code generated by command: go run asm.go -out filter.s -stubs filter_stub.go. DO NOT EDIT.

package cuckoo

// NumFilled returns the total number of filled entries in all buckets in a Cuckoo filter.
func NumFilled(entries []byte) uint
